using System.Text.Json.Serialization;

namespace CloudNimble.ChromeEssentials.Protocol;

/// <summary>
/// Parameters for the <c>Input.dispatchKeyEvent</c> CDP command.
/// Dispatches a key event to the page.
/// </summary>
public sealed class KeyEventParams
{
    /// <summary>
    /// Gets or sets the type of the key event.
    /// Allowed values: <c>"keyDown"</c>, <c>"keyUp"</c>, <c>"rawKeyDown"</c>, <c>"char"</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "";

    /// <summary>
    /// Gets or sets the bit field representing pressed modifier keys.
    /// Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
    /// </summary>
    [JsonPropertyName("modifiers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int Modifiers { get; set; }

    /// <summary>
    /// Gets or sets the text as generated by processing a virtual key code with a keyboard layout.
    /// Not needed for keyUp and rawKeyDown events (default: "").
    /// </summary>
    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Text { get; set; }

    /// <summary>
    /// Gets or sets the text that would have been generated by the keyboard if no modifiers were pressed
    /// (except for shift). Useful for shortcut (accelerator) key handling (default: "").
    /// </summary>
    [JsonPropertyName("unmodifiedText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? UnmodifiedText { get; set; }

    /// <summary>
    /// Gets or sets the unique DOM defined string value for each physical key (e.g., <c>"ArrowLeft"</c>) (default: "").
    /// </summary>
    [JsonPropertyName("key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Key { get; set; }

    /// <summary>
    /// Gets or sets the unique DOM defined string value describing the meaning of the key in the context
    /// of active modifiers, keyboard layout, etc (e.g., <c>"KeyA"</c>) (default: "").
    /// </summary>
    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Code { get; set; }

    /// <summary>
    /// Gets or sets the Windows virtual key code (default: 0).
    /// </summary>
    [JsonPropertyName("windowsVirtualKeyCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int WindowsVirtualKeyCode { get; set; }

    /// <summary>
    /// Gets or sets the native virtual key code (default: 0).
    /// </summary>
    [JsonPropertyName("nativeVirtualKeyCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int NativeVirtualKeyCode { get; set; }
}
