using System.Text.Json.Serialization;

namespace CloudNimble.ChromeEssentials.Protocol;

/// <summary>
/// Parameters for the <c>Input.dispatchKeyEvent</c> CDP command.
/// Dispatches a synthetic keyboard event to the page.
/// </summary>
public sealed class KeyEventParams
{
    /// <summary>
    /// Gets or sets the type of key event (<c>"keyDown"</c>, <c>"keyUp"</c>, <c>"rawKeyDown"</c>, or <c>"char"</c>).
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "";

    /// <summary>
    /// Gets or sets the bit field representing pressed modifier keys.
    /// 1 = Alt, 2 = Ctrl, 4 = Meta/Command, 8 = Shift.
    /// </summary>
    [JsonPropertyName("modifiers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int Modifiers { get; set; }

    /// <summary>
    /// Gets or sets the text generated by processing the virtual key code with a keyboard layout.
    /// Not needed for modifier key events.
    /// </summary>
    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Text { get; set; }

    /// <summary>
    /// Gets or sets the text that would have been generated by the keyboard if no modifiers were pressed.
    /// </summary>
    [JsonPropertyName("unmodifiedText")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? UnmodifiedText { get; set; }

    /// <summary>
    /// Gets or sets the unique DOM-defined key value (e.g., <c>"Enter"</c>, <c>"Tab"</c>, <c>"ArrowDown"</c>).
    /// See https://www.w3.org/TR/uievents-key/.
    /// </summary>
    [JsonPropertyName("key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Key { get; set; }

    /// <summary>
    /// Gets or sets the unique DOM-defined code value (e.g., <c>"KeyA"</c>, <c>"Enter"</c>).
    /// See https://www.w3.org/TR/uievents-code/.
    /// </summary>
    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Code { get; set; }

    /// <summary>
    /// Gets or sets the Windows virtual key code (e.g., 13 for Enter, 9 for Tab).
    /// </summary>
    [JsonPropertyName("windowsVirtualKeyCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int WindowsVirtualKeyCode { get; set; }

    /// <summary>
    /// Gets or sets the native virtual key code.
    /// </summary>
    [JsonPropertyName("nativeVirtualKeyCode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int NativeVirtualKeyCode { get; set; }
}
